### ISSUE TITLE
Failed to parse YAML from [gs://runtime-builders/experiments.yaml]: mapping values are not allowed here

### ISSUE THREAD

**Issue by hpate-omicron** [GoogleCloudPlatform/elixir-runtime#29]
We're using this elixir-runtime, and we just started getting this error today.  We haven't made any recent changes to the `app.yaml`, it seems like the error is coming from `gs://runtime-builders/experiments.yaml`

```
$ gcloud app deploy app.yaml --verbosity debug
27 DEBUG: Running [gcloud.app.deploy] with arguments: [--verbosity: "debug", DEPLOYABLES:1: "[u'app.yaml']"]
28 DEBUG: Loading runtimes experiment config from [gs://runtime-builders/experiments.yaml]
29 INFO: Reading [<googlecloudsdk.api_lib.storage.storage_util.ObjectReference object at 0x7f136c316710>]
30 DEBUG: (gcloud.app.deploy) Failed to parse YAML from [gs://runtime-builders/experiments.yaml]: mapping values are not allowed here
31   in "<file>", line 2, column 14
32 Traceback (most recent call last):
33   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
34     resources = calliope_command.Run(cli=self, args=args)
35   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 798, in Run
36     resources = command_instance.Run(args)
37   File "/usr/lib/google-cloud-sdk/lib/surface/app/deploy.py", line 100, in Run
38     self._ServerSideExperimentEnabled()):
39   File "/usr/lib/google-cloud-sdk/lib/surface/app/deploy.py", line 126, in _ServerSideExperimentEnabled
40     runtimes_builder_root)
41   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/runtime_builders.py", line 519, in LoadFromURI
42     data = yaml.load(f, file_hint=uri)
43   File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/yaml.py", line 132, in load
44     raise YAMLParseError(e, f=file_hint)
45 YAMLParseError: Failed to parse YAML from [gs://runtime-builders/experiments.yaml]: mapping values are not allowed here
46   in "<file>", line 2, column 14
47 ERROR: (gcloud.app.deploy) Failed to parse YAML from [gs://runtime-builders/experiments.yaml]: mapping values are not allowed here
48   in "<file>", line 2, column 14```

**Comment by hpate-omicron** [comment]
Seems to have been fixed, new builds are not hitting the issue
